image: docker:stable

variables:
  DOCKER_HOST: tcp://localhost:2375/  # Kubernetes executor
  # DOCKER_HOST: tcp://docker:2375/  # non- Kubernetes executor
  DOCKER_DRIVER: overlay2  # better performance for dind

stages:
  - build
  - deploy

services:
  - amr-registry.caas.intel.com/caas/docker:stable-dind

ubuntu1804:
  stage: build
  only:
    - branches
    - tags
  tags: ['caas', 'docker', 'linux']
  variables:
    BUILDER_IMAGE: ${HARBOR_HOST}/${HARBOR_PROJECT}/${CI_PROJECT_NAME}-${CI_JOB_NAME}
    # Workaround for https://gitlab.com/gitlab-org/gitlab-ce/issues/27436
    HARBOR_USER2: ${HARBOR_USER}
    HARBOR_TOKEN2: ${HARBOR_TOKEN}
  script:
    - docker login -u ${HARBOR_USER2} -p ${HARBOR_TOKEN2} ${HARBOR_HOST}
    - docker info
    - sh ./ci-image.sh
    - docker run
        --rm
        -v ${PWD}:/root/project
        -w /root/project
        --env-file ./ci-env
        -v /ccache:/ccache
        -e CCACHE_DIR=/ccache
        -e CCACHE_BASEDIR=/root/project
        ${BUILDER_IMAGE}:${CI_COMMIT_REF_SLUG}
        ./ci-build.sh
    - docker push ${BUILDER_IMAGE}:${CI_COMMIT_REF_SLUG}
    - docker push ${BUILDER_IMAGE}:latest
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - intel-level-zero-perftests-*-Source.*
      - intel-level-zero-perftests-*-Linux.*

deploy-artifactory:
  stage: deploy
  only:
    - tags
  tags: ['caas', 'docker', 'linux']
  image: retgits/jfrog-cli:1.23.2-alpine
  script:
    - jfrog rt config
        --url ${ARTIFACTORY_URL}
        --apikey ${ARTIFACTORY_APIKEY}
        artifactory
    - jfrog rt build-add-git ${CI_PROJECT_NAME} ${CI_PIPELINE_ID}
    - jfrog rt upload
        --build-name ${CI_PROJECT_NAME}
        --build-number ${CI_PIPELINE_ID}
        "./intel-level-zero-perftests-*.tar.gz"
        ${ARTIFACTORY_REPO}/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}/
    - echo "Build assets uploaded to ${ARTIFACTORY_URL}/${ARTIFACTORY_REPO}/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}"
    - jfrog rt build-publish ${CI_PROJECT_NAME} ${CI_PIPELINE_ID}
