image: docker:stable

variables:
  # When using dind service we need to instruct docker, to talk with the
  # daemon started inside of the service. The daemon is available with
  # a network connection instead of the default /var/run/docker.sock socket.
  #
  # The 'docker' hostname is the alias of the service container as described at
  # https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#accessing-the-services
  #
  # Note that if you're using the Kubernetes executor, the variable should be set to
  # tcp://localhost:2375/ because of how the Kubernetes executor connects services
  # to the job container
  DOCKER_HOST: tcp://localhost:2375/
  #
  # For non-Kubernetes executors, we use tcp://docker:2375/
  # DOCKER_HOST: tcp://docker:2375/
  # When using dind, it's wise to use the overlayfs driver for
  # improved performance.
  DOCKER_DRIVER: overlay2

stages:
  - build

services:
  - name: docker:dind
    entrypoint: ["dockerd-entrypoint.sh"]
    command: ["--insecure-registry", "registry.citadel.ra.intel.com"] # workaround for docker:dind not having Intel root CA in it

before_script:
  - docker login -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD} ${REGISTRY_HOST}
  - docker info

ubuntu1804:
  stage: build
  only: ['tags', 'merge_requests']
  tags: ['caas', 'docker', 'linux']
  variables:
    BUILDER_IMAGE: ${REGISTRY_HOST}/${CI_PROJECT_NAME}-${CI_JOB_NAME}
  script:
    - sh ./ci-image.sh
    - docker run --rm -v ${PWD}:/root/project -w /root/project --env-file ./ci-env ${BUILDER_IMAGE}:${CI_COMMIT_REF_SLUG} ./ci-build.sh
    - docker push ${BUILDER_IMAGE}:${CI_COMMIT_REF_SLUG}
    - docker push ${BUILDER_IMAGE}:latest
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - build/intel-loki-perftests-*-Source.*
      - build/intel-loki-perftests-*-Linux.*
