# YAML test configuration
#
# Specify default and specific configuration parameters for pre-merge test
# execution. The default configuration is specified under "default", and
# configuration for each case is specified under the suite name -> case name.
# Suite names are any top-level results reported by --gtest_list_tests,
# including prefixes from parameterization instantiations.
#
# Example:
#
# TestP2PConcurrentAccess/xeP2PKernelTestsConcurrentAccess:
#   GivenP2PDevicesWhenConcurrentAccessesOfPeerMemoryThenSuccessIsReturned:
#     timeout: 60

---
default:
  timeout: 60
...
