FROM python:3.8.1-buster

ENV HTTP_PROXY http://proxy-chain.intel.com:911
ENV HTTPS_PROXY http://proxy-chain.intel.com:911

ARG PYLZT_GITLABTOKEN_USER
ENV PYLZT_GITLABTOKEN_USER=$PYLZT_GITLABTOKEN_USER

ARG PYLZT_GITLABTOKEN_PASSWORD
ENV PYLZT_GITLABTOKEN_PASSWORD=$PYLZT_GITLABTOKEN_PASSWORD

RUN pip install git+https://${PYLZT_GITLABTOKEN_USER}:${PYLZT_GITLABTOKEN_PASSWORD}@gitlab.devtools.intel.com/ledettwy/pylzt.git@40ad0a8b69c97ee0ec177b53d936168650cca281
